name: CI – Train Model

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Conda & MLflow
        run: |
          sudo apt update
          sudo apt install -y wget
          wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
          bash miniconda.sh -b -p $HOME/miniconda
          echo "$HOME/miniconda/bin" >> $GITHUB_PATH
          source "$HOME/miniconda/etc/profile.d/conda.sh"
          conda init bash
          conda --version
          conda install -y -c conda-forge mlflow

      - name: Run MLflow Project with Conda
        run: |
          mlflow run MLProject \
            -P data_path=namadataset_preprocessing/automobile_preprocessed.csv \
            -P n_estimators=100 \
            -P max_depth=10

      - name: Archive MLflow runs
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-runs
          path: mlruns/